spring:
  application:
    name: product-api
  cache:
    type: hazelcast
    hazelcast:
      config: classpath:hazelcast.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: app
    password: s3cr3t
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        cache:
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
          use_second_level_cache: true

server:
  port: 8090